# **Seminario de métodos computacionales para lenguas amerindias**
### Roberto Zariquiey Biondi, rzariquiey@pucp.edu.pe 
### Javier Vera Zúñiga, jveraz@pucp.edu.pe

Bases de datos

- bases de datos abiertas - ¿open science?
- phoible (correlación inventario vs. población), sails, autotype, concepticon, glottobank, wals, saphon (sudamérica) 
- ver lexibank, numeralbank
- preguntas sobre wals: ideas cuantitativas
- ética de las bases de datos - autores difusos!
- se esconden las citas, y el tipo de citas
- datos tabulados! (pandas, diccionarios y cálculos)
- diferencias de cobertura!
- cobertura de rasgos en wals: comparación! (proyecto)
- aspectos políticos en la construcción de bases de datos

## Datos de [Sails](https://sails.clld.org/) y [Glottolog](https://glottolog.org/), diccionarios y [pandas](https://pandas.pydata.org/) (también [ver](https://pandas.pydata.org/docs/user_guide/index.html))

### [Wals!](https://raw.githubusercontent.com/cldf-dataset/wals/master/cldf/values.csv) 
Preguntas de **cobertura!**

In [27]:
## importamos la librería
import pandas as pd

## archivo descargado de glottolog
wals = pd.read_csv('values_wals.csv')

In [28]:
wals

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Example_ID
0,81A-aab,aab,81A,2,81A-2,NaN,Nekitel-1985[94],NaN
1,82A-aab,aab,82A,1,82A-1,NaN,Nekitel-1985[94],NaN
2,83A-aab,aab,83A,2,83A-2,NaN,Nekitel-1985[94],NaN
3,87A-aab,aab,87A,2,87A-2,NaN,Nekitel-1985[95],NaN
4,88A-aab,aab,88A,2,88A-2,NaN,Nekitel-1985[95],NaN
...,...,...,...,...,...,...,...,...
76470,144B-zzo,zzo,144B,3,144B-3,NaN,Sonnenschein-2005[114],NaN
76471,144T-zzo,zzo,144T,1,144T-1,NaN,Sonnenschein-2005[114],NaN
76472,144V-zzo,zzo,144V,1,144V-1,NaN,Sonnenschein-2005[114],NaN
76473,144W-zzo,zzo,144W,6,144W-6,NaN,Sonnenschein-2005[114],NaN
76474,144X-zzo,zzo,144X,4,144X-4,NaN,Sonnenschein-2005[114],NaN

### Glottolog!
**Pregunta 1.** ¿Cómo obtenemos una lista de lenguas de Sudamérica?

In [1]:
## ¿Cómo se ven los datos de Glottolog?

## importamos la librería
import pandas as pd

## archivo descargado de glottolog
glottolog = pd.read_csv('languages_and_dialects_geo.csv')

In [2]:
## columnas del dataframe glottolog

glottolog.columns

Index(['glottocode', 'name', 'isocodes', 'level', 'macroarea', 'latitude',
       'longitude'],
      dtype='object')

In [3]:
glottolog

,glottocode,name,isocodes,level,macroarea,latitude,longitude
0,3adt1234,3Ad-Tekles,NaN,dialect,Africa,NaN,NaN
1,aala1237,Aalawa,NaN,dialect,Papunesia,NaN,NaN
2,aant1238,Aantantara,NaN,dialect,Papunesia,NaN,NaN
3,aari1239,Aari,aiw,language,Africa,5.95034,36.5721
4,aari1240,Aariya,aay,language,Eurasia,NaN,NaN
...,...,...,...,...,...,...,...
21647,zuwa1238,Zuwadza,NaN,dialect,Papunesia,NaN,NaN
21648,zwal1238,Zwall,NaN,dialect,Africa,NaN,NaN
21649,zyph1238,Zyphe,zyp,language,Eurasia,22.52400,93.2640
21650,zyud1238,Zyuzdin,NaN,dialect,Eurasia,NaN,NaN
21651,huaa1249,ǂHua,NaN,dialect,Africa,NaN,NaN

In [4]:
## ¿Cuáles son los valores de la columna "macroarea"?

## lista vacía para guardar las macroáreas
macroareas_unicas = []

## recorremos los datos de la columna
for m in glottolog['macroarea']:
    ## si no está, lo guardamos
    if m not in macroareas_unicas:
        ## guardamos en la lista
        macroareas_unicas += [m]

In [5]:
macroareas_unicas

['Africa',
 'Papunesia',
 'Eurasia',
 'South America',
 'North America',
 'Australia',
 nan]

In [6]:
## otra forma

macroareas_unicas = set(glottolog['macroarea'])

In [7]:
macroareas_unicas

{'Africa',
 'Australia',
 'Eurasia',
 'North America',
 'Papunesia',
 'South America',
 nan}

In [8]:
## ¿Cómo filtramos las lenguas de Sudamérica?

## accedemos a la columna "macroarea", y filtramos las filas que tengan "South America"
glottolog = glottolog[glottolog['macroarea'] == 'South America']

In [9]:
glottolog

,glottocode,name,isocodes,level,macroarea,latitude,longitude
22,aban1243,Abancay,NaN,dialect,South America,NaN,NaN
47,abip1241,Abipon,axb,language,South America,-29.000000,-61.000000
81,acha1250,Achagua,aca,language,South America,4.386490,-72.200500
83,ache1246,Aché,guq,language,South America,-25.586500,-56.469700
91,achu1249,Achuar,NaN,dialect,South America,NaN,NaN
...,...,...,...,...,...,...,...
21454,yuru1263,Yurutí,yui,language,South America,0.735585,-69.695500
21497,zamu1245,Zamuco,NaN,language,South America,-18.910444,-59.439698
21512,zapa1253,Záparo,zro,language,South America,-1.998710,-76.364000
21607,zoee1240,Zo'é,pto,language,South America,-1.772080,-55.507460
21617,zoro1244,Zoró,NaN,dialect,South America,NaN,NaN

In [10]:
## ¿Hay 1164 lenguas en Sudamérica? Filtremos por ciertas columnas: glottocode, name, isocode, latitude, longitude

glottolog = glottolog[['glottocode', 'name', 'isocodes', 'latitude', 'longitude']]

In [11]:
glottolog

      glottocode     name isocodes   latitude  longitude
22      aban1243  Abancay      NaN        NaN        NaN
47      abip1241   Abipon      axb -29.000000 -61.000000
81      acha1250  Achagua      aca   4.386490 -72.200500
83      ache1246     Aché      guq -25.586500 -56.469700
91      achu1249   Achuar      NaN        NaN        NaN
...          ...      ...      ...        ...        ...
21454   yuru1263   Yurutí      yui   0.735585 -69.695500
21497   zamu1245   Zamuco      NaN -18.910444 -59.439698
21512   zapa1253   Záparo      zro  -1.998710 -76.364000
21607   zoee1240     Zo'é      pto  -1.772080 -55.507460
21617   zoro1244     Zoró      NaN        NaN        NaN

[1164 rows x 5 columns]

In [12]:
## ahora, filtramos las filas que tienen datos faltantes

glottolog = glottolog.dropna()

In [13]:
## ¿Se ve razonable este número?

glottolog

      glottocode            name isocodes   latitude  longitude
47      abip1241          Abipon      axb -29.000000  -61.00000
81      acha1250         Achagua      aca   4.386490  -72.20050
83      ache1246            Aché      guq -25.586500  -56.46970
92      achu1248  Achuar-Shiwiar      acu  -2.826460  -77.26410
98      acro1239           Acroá      acs -12.594000  -40.21445
...          ...             ...      ...        ...        ...
21445   yuqu1240           Yuqui      yuq -16.787500  -64.94380
21446   yura1255        Yuracaré      yuz -16.747900  -65.12240
21454   yuru1263          Yurutí      yui   0.735585  -69.69550
21512   zapa1253          Záparo      zro  -1.998710  -76.36400
21607   zoee1240            Zo'é      pto  -1.772080  -55.50746

[547 rows x 5 columns]

In [14]:
## una lista de lenguas de Sudamérica

glottocode_lenguas_SA = list(glottolog['glottocode'])

In [15]:
glottocode_lenguas_SA[:10]

['abip1241',
 'acha1250',
 'ache1246',
 'achu1248',
 'acro1239',
 'abis1238',
 'agav1236',
 'agua1251',
 'agua1253',
 'aika1237']

**Pregunta 2.** ¿Cómo organizamos la lista de lenguas de Sudamérica en familias lingüísticas?

In [16]:
## archivo descargado de glottolog
languoid = pd.read_csv('languoid.csv')

In [17]:
languoid

,id,family_id,parent_id,name,bookkeeping,level,latitude,longitude,iso639P3code,description,markup_description,child_family_count,child_language_count,child_dialect_count,country_ids
0,3adt1234,afro1255,nort3292,3Ad-Tekles,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
1,aala1237,aust1307,ramo1244,Aalawa,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
2,aant1238,nucl1709,nort2920,Aantantara,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
3,aari1238,sout2845,ahkk1235,Aari-Gayil,False,family,NaN,NaN,aiz,NaN,NaN,0,2,0,NaN
4,aari1239,sout2845,aari1238,Aari,False,language,5.95034,36.5721,aiw,NaN,NaN,0,0,0,ET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26280,zuti1239,tupi1275,guaj1255,Guajajára of Zutiua,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
26281,zuwa1238,koia1260,omie1241,Zuwadza,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
26282,zwal1238,atla1278,shal1242,Zwall,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
26283,zyph1238,sino1245,nucl1757,Zyphe,False,language,22.52400,93.2640,zyp,NaN,NaN,0,0,2,IN MM
26284,zyud1238,ural1272,komi1269,Zyuzdin,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN

In [18]:
## filtremos la columna "id" con las lenguas de la lista glottocode_lenguas_SA

languoid = languoid[languoid['id'].isin(glottocode_lenguas_SA)]

In [19]:
languoid

,id,family_id,parent_id,name,bookkeeping,level,latitude,longitude,iso639P3code,description,markup_description,child_family_count,child_language_count,child_dialect_count,country_ids
54,abip1241,guai1249,guai1250,Abipon,False,language,-29.000000,-61.000000,axb,NaN,NaN,0,0,0,AR
55,abis1238,NaN,NaN,Aewa,False,language,-1.284096,-75.084405,ash,NaN,NaN,0,0,0,PE
93,acha1250,araw1281,piap1247,Achagua,False,language,4.386490,-72.200500,aca,NaN,NaN,0,0,0,CO
97,ache1246,tupi1275,tupi1277,Aché,False,language,-25.586500,-56.469700,guq,NaN,NaN,0,0,0,PY
107,achu1248,jiva1245,shua1256,Achuar-Shiwiar,False,language,-2.826460,-77.264100,acu,NaN,NaN,0,0,2,EC PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26045,yura1255,NaN,NaN,Yuracaré,False,language,-16.747900,-65.122400,yuz,NaN,NaN,0,0,2,BO
26053,yuru1263,tuca1253,tuyu1245,Yurutí,False,language,0.735585,-69.695500,yui,NaN,NaN,0,0,0,BR CO
26063,yuwa1244,NaN,NaN,Hoti,False,language,5.638790,-65.426700,yau,NaN,NaN,0,0,0,VE
26124,zapa1253,zapa1251,zapa1252,Záparo,False,language,-1.998710,-76.364000,zro,NaN,NaN,0,0,0,EC PE
26232,zoee1240,tupi1275,zoee1241,Zo'é,False,language,-1.772080,-55.507460,pto,NaN,NaN,0,0,0,BR

In [20]:
## arreglemos los NaN

## reemplazamos con un string 
languoid.fillna('unk', inplace=True)

C:\Users\jxver\anaconda3\lib\site-packages\pandas\core\frame.py:4462: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [21]:
languoid

,id,family_id,parent_id,name,bookkeeping,level,latitude,longitude,iso639P3code,description,markup_description,child_family_count,child_language_count,child_dialect_count,country_ids
54,abip1241,guai1249,guai1250,Abipon,False,language,-29.000000,-61.000000,axb,unk,unk,0,0,0,AR
55,abis1238,unk,unk,Aewa,False,language,-1.284096,-75.084405,ash,unk,unk,0,0,0,PE
93,acha1250,araw1281,piap1247,Achagua,False,language,4.386490,-72.200500,aca,unk,unk,0,0,0,CO
97,ache1246,tupi1275,tupi1277,Aché,False,language,-25.586500,-56.469700,guq,unk,unk,0,0,0,PY
107,achu1248,jiva1245,shua1256,Achuar-Shiwiar,False,language,-2.826460,-77.264100,acu,unk,unk,0,0,2,EC PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26045,yura1255,unk,unk,Yuracaré,False,language,-16.747900,-65.122400,yuz,unk,unk,0,0,2,BO
26053,yuru1263,tuca1253,tuyu1245,Yurutí,False,language,0.735585,-69.695500,yui,unk,unk,0,0,0,BR CO
26063,yuwa1244,unk,unk,Hoti,False,language,5.638790,-65.426700,yau,unk,unk,0,0,0,VE
26124,zapa1253,zapa1251,zapa1252,Záparo,False,language,-1.998710,-76.364000,zro,unk,unk,0,0,0,EC PE
26232,zoee1240,tupi1275,zoee1241,Zo'é,False,language,-1.772080,-55.507460,pto,unk,unk,0,0,0,BR

In [22]:
## construyamos un diccionario glottocode:glottocode_familia

dict_glottocode_fam = {}

## usamos las dos primeras columnas

## recorremos las lenguas de la primera columna
for i in range(len(languoid['id'])):
    ## accedemos a la lengua
    lengua = list(languoid['id'])[i]
    ## accedemos a la familia
    familia = list(languoid['family_id'])[i]
    ## guardamos la información en el diccionario
    dict_glottocode_fam[lengua] = familia

In [23]:
dict_glottocode_fam

{'abip1241': 'guai1249',
 'abis1238': 'unk',
 'acha1250': 'araw1281',
 'ache1246': 'tupi1275',
 'achu1248': 'jiva1245',
 'acro1239': 'nucl1710',
 'agav1236': 'unat1236',
 'agua1251': 'unat1236',
 'agua1253': 'jiva1245',
 'aika1237': 'unk',
 'ajyi1238': 'araw1281',
 'akaw1239': 'cari1283',
 'akun1241': 'tupi1275',
 'akur1238': 'cari1283',
 'alap1235': 'unat1236',
 'amah1246': 'pano1259',
 'aman1266': 'tupi1275',
 'amar1274': 'hara1260',
 'ambo1252': 'quec1387',
 'amun1246': 'tupi1275',
 'anam1249': 'tupi1275',
 'anda1286': 'unk',
 'ando1255': 'zapa1251',
 'ando1256': 'unk',
 'anga1316': 'leng1261',
 'ango1257': 'chib1249',
 'anse1238': 'choc1280',
 'apal1257': 'cari1283',
 'apia1248': 'tupi1275',
 'apin1244': 'nucl1710',
 'apur1254': 'araw1281',
 'arab1268': 'zapa1251',
 'arao1248': 'pano1259',
 'arap1275': 'tuca1253',
 'araw1273': 'tupi1275',
 'araw1276': 'araw1281',
 'areq1237': 'quec1387',
 'arge1236': 'sign1238',
 'arhu1242': 'chib1249',
 'arik1264': 'tupi1275',
 'arik1265': 'nucl1710',
 'arma1244': 'unat1236',
 'arua1261': 'tupi1275',
 'arua1263': 'araw1282',
 'arut1244': 'unk',
 'asha1243': 'araw1281',
 'ashe1272': 'araw1281',
 'ashe1273': 'araw1281',
 'ator1244': 'araw1281',
 'atsa1242': 'pano1259',
 'aura1243': 'tupi1275',
 'aush1242': 'zapa1251',
 'avac1239': 'tupi1275',
 'awac1239': 'barb1265',
 'awet1244': 'tupi1275',
 'ayac1239': 'quec1387',
 'ayor1240': 'zamu1243',
 'baka1277': 'cari1283',
 'bani1254': 'araw1281',
 'bani1255': 'araw1281',
 'bara1380': 'tuca1253',
 'barb1242': 'unat1236',
 'bare1276': 'araw1281',
 'bari1297': 'chib1249',
 'barr1251': 'chib1249',
 'baur1253': 'araw1281',
 'berb1259': 'indo1319',
 'boli1236': 'sign1238',
 'bora1263': 'bora1262',
 'bord1248': 'chib1249',
 'boro1282': 'boro1281',
 'braz1236': 'sign1238',
 'cabi1241': 'araw1281',
 'cacu1241': 'kaku1242',
 'cafu1238': 'indo1319',
 'cagu1236': 'book1242',
 'cahu1268': 'zapa1251',
 'caja1238': 'quec1387',
 'caja1239': 'quec1387',
 'cald1236': 'quec1387',
 'call1235': 'spee1234',
 'cams1241': 'unk',
 'cana1262': 'quec1387',
 'cand1248': 'unk',
 'cane1242': 'nucl1710',
 'cani1243': 'unk',
 'capa1241': 'pano1259',
 'caqu1242': 'araw1281',
 'cara1245': 'uncl1493',
 'cara1271': 'choc1280',
 'cara1272': 'tuca1253',
 'cari1275': 'indo1319',
 'cari1276': 'aust1307',
 'cari1279': 'cari1283',
 'cash1251': 'pano1259',
 'cash1254': 'pano1259',
 'cauc1241': 'book1242',
 'cavi1250': 'pano1259',
 'cayu1262': 'unk',
 'cent2142': 'ayma1253',
 'cent2150': 'chib1249',
 'chac1249': 'barb1265',
 'chac1250': 'quec1387',
 'chac1251': 'pano1259',
 'chai1253': 'cari1283',
 'cham1315': 'zamu1243',
 'cham1318': 'araw1281',
 'chan1322': 'araw1281',
 'chay1248': 'cahu1265',
 'chib1270': 'chib1249',
 'chil1264': 'sign1238',
 'chil1283': 'book1242',
 'chim1302': 'quec1387',
 'chim1309': 'chib1249',
 'chin1483': 'quec1387',
 'chip1236': 'book1242',
 'chip1262': 'uruc1242',
 'chiq1248': 'chiq1253',
 'chiq1249': 'quec1387',
 'chir1286': 'tupi1275',
 'chol1284': 'hibi1242',
 'cint1239': 'tupi1275',
 'clas1251': 'quec1387',
 'coca1259': 'tupi1275',
 'cofa1242': 'unk',
 'cogu1240': 'chib1249',
 'colo1249': 'sign1238',
 'colo1254': 'indo1319',
 'colo1256': 'barb1265',
 'coro1247': 'quec1387',
 'coro1248': 'nucl1710',
 'coxi1236': 'book1242',
 'coya1241': 'book1242',
 'creo1235': 'indo1319',
 'cube1242': 'tuca1253',
 'cuib1242': 'guah1252',
 'culi1244': 'araw1282',
 'cuma1240': 'cari1283',
 'cume1234': 'book1242',
 'curr1243': 'araw1281',
 'cusc1236': 'quec1387',
 'daww1239': 'nada1235',
 'deni1241': 'araw1282',
 'desa1247': 'tuca1253',
 'djeo1235': 'nucl1710',
 'east2551': 'quec1387',
 'east2555': 'tupi1275',
 'ecua1243': 'sign1238',
 'embe1259': 'choc1280',
 'embe1260': 'choc1280',
 'embe1261': 'choc1280',
 'embe1262': 'choc1280',
 'emer1243': 'tupi1275',
 'emok1238': 'book1242',
 'enap1235': 'cari1283',
 'enaw1238': 'araw1281',
 'epen1239': 'choc1280',
 'esee1248': 'pano1259',
 'fuln1247': 'unk',
 'gali1262': 'cari1283',
 'gavi1246': 'tupi1275',
 'guah1255': 'guah1252',
 'guaj1255': 'tupi1275',
 'guaj1256': 'tupi1275',
 'guam1248': 'barb1265',
 'guan1268': 'leng1261',
 'guan1269': 'tuca1253',
 'guan1270': 'araw1281',
 'guar1292': 'tupi1275',
 'guar1293': 'araw1281',
 'guat1253': 'unk',
 'guay1257': 'guah1252',
 'guia1246': 'indo1319',
 'hibi1243': 'hibi1242',
 'hima1247': 'unat1236',
 'hixk1239': 'cari1283',
 'huac1244': 'hara1260',
 'hual1241': 'quec1387',
 'huam1247': 'jiva1245',
 'huam1248': 'quec1387',
 'huay1240': 'quec1387',
 'huay1241': 'quec1387',
 'huil1244': 'arau1255',
 'hupd1244': 'nada1235',
 'iapa1241': 'book1242',
 'igna1246': 'araw1281',
 'ikpe1245': 'cari1283',
 'imba1240': 'quec1387',
 'inap1242': 'araw1281',
 'inga1252': 'quec1387',
 'iqui1243': 'zapa1251',
 'iran1263': 'unk',
 'isco1239': 'pano1259',
 'iten1243': 'chap1271',
 'iton1250': 'unk',
 'iyoj1235': 'mata1289',
 'iyow1239': 'mata1289',
 'jama1261': 'araw1282',
 'japr1238': 'cari1283',
 'jaqa1244': 'ayma1253',
 'jauj1238': 'quec1387',
 'jebe1250': 'cahu1265',
 'jora1240': 'tupi1275',
 'juma1249': 'tupi1275',
 'jung1240': 'quec1387',
 'juru1256': 'tupi1275',
 'kabi1264': 'book1242',
 'kadi1248': 'guai1249',
 'kaim1235': 'uncl1493',
 'kain1272': 'nucl1710',
 'kaiw1246': 'tupi1275',
 'kaka1269': 'book1242',
 'kama1372': 'kama1371',
 'kama1373': 'tupi1275',
 'kamb1239': 'uncl1493',
 'kamb1287': 'book1242',
 'kana1291': 'katu1274',
 'kano1245': 'unk',
 'kapi1248': 'uncl1493',
 'kara1475': 'unat1236',
 'kara1500': 'nucl1710',
 'kari1255': 'uncl1493',
 'kari1301': 'indo1319',
 'kari1309': 'book1242',
 'kari1311': 'tupi1275',
 'kari1317': 'tupi1275',
 'karo1305': 'tupi1275',
 'kata1270': 'katu1274',
 'kaxa1239': 'pano1259',
 'kaxu1237': 'cari1283',
 'kaya1329': 'tupi1275',
 'kaya1330': 'nucl1710',
 'kepk1241': 'tupi1275',
 'kore1283': 'tuca1253',
 'koru1247': 'pano1259',
 'krah1246': 'nucl1710',
 'kren1239': 'nucl1710',
 'krey1238': 'nucl1710',
 'krik1239': 'nucl1710',
 'kuik1246': 'cari1283',
 'kuli1255': 'pano1259',
 'kunz1244': 'unk',
 'kuru1309': 'tupi1275',
 'kwaz1243': 'unk',
 'kwin1243': 'indo1319',
 'lako1248': 'namb1299',
 'lamb1276': 'quec1387',
 'latu1238': 'namb1299',
 'leco1242': 'unk',
 'loja1235': 'quec1387',
 'lore1243': 'indo1319',
 'lule1238': 'unk',
 'maca1259': 'guah1252',
 'maca1260': 'mata1289',
 'maca1261': 'tuca1253',
 'mach1267': 'araw1281',
 'mach1268': 'araw1281',
 'maco1239': 'sali1297',
 'macu1259': 'cari1283',
 'macu1260': 'tuca1253',
 'maku1246': 'unk',
 'maku1278': 'tupi1275',
 'mala1522': 'chib1249',
 'mama1278': 'namb1299',
 'mand1448': 'araw1281',
 'mapi1252': 'araw1281',
 'mapo1246': 'cari1283',
 'mapu1245': 'arau1255',
 'maqu1238': 'cari1283',
 'marg1254': 'quec1387',
 'mari1442': 'tupi1275',
 'maru1252': 'pano1259',
 'mash1270': 'araw1281',
 'mask1241': 'book1242',
 'mati1253': 'cari1283',
 'mati1255': 'pano1259',
 'mato1253': 'unk',
 'mats1244': 'pano1259',
 'mawa1271': 'book1242',
 'maxa1247': 'nucl1710',
 'mbya1239': 'tupi1275',
 'medi1245': 'mixe1287',
 'mehi1240': 'araw1281',
 'miar1236': 'unat1236',
 'mini1256': 'huit1251',
 'miri1270': 'tuca1253',
 'moch1259': 'unk',
 'moco1246': 'guai1249',
 'more1262': 'unat1236',
 'mose1249': 'unk',
 'movi1243': 'unk',
 'muin1242': 'bora1262',
 'mund1330': 'tupi1275',
 'muni1258': 'unk',
 'muru1274': 'huit1251',
 'nade1244': 'nada1235',
 'nant1250': 'araw1281',
 'napo1242': 'quec1387',
 'nata1238': 'book1242',
 'ndyu1241': 'pidg1258',
 'ndyu1242': 'indo1319',
 'nhen1239': 'tupi1275',
 'nina1238': 'yano1268',
 'niva1238': 'mata1289',
 'noca1240': 'book1242',
 'noma1263': 'araw1281',
 'nonu1241': 'huit1251',
 'nort2971': 'leng1261',
 'nort2972': 'choc1280',
 'nort2973': 'quec1387',
 'nort2976': 'quec1387',
 'nort2979': 'quec1387',
 'nort2980': 'quec1387',
 'nucl1668': 'book1242',
 'nuka1242': 'kaku1242',
 'nuku1263': 'pano1259',
 'nupo1240': 'huit1251',
 'ocai1244': 'huit1251',
 'ofay1240': 'nucl1710',
 'omag1248': 'tupi1275',
 'omej1234': 'book1242',
 'omur1241': 'unk',
 'onaa1245': 'chon1288',
 'orej1242': 'tuca1253',
 'orow1243': 'chap1271',
 'otii1244': 'unk',
 'otuk1240': 'boro1281',
 'paca1245': 'quec1387',
 'paca1246': 'pano1259',
 'paez1247': 'unk',
 'pait1247': 'tupi1275',
 'pale1260': 'indo1319',
 'pali1279': 'araw1281',
 'pana1306': 'quec1387',
 'pana1307': 'nucl1710',
 'pank1235': 'unat1236',
 'pank1250': 'unk',
 'pano1254': 'pano1259',
 'pano1255': 'pano1259',
 'papa1263': 'unat1236',
 'papi1253': 'indo1319',
 'para1310': 'cari1283',
 'para1311': 'tupi1275',
 'para1312': 'tupi1275',
 'para1313': 'tupi1275',
 'para1315': 'nucl1710',
 'para1316': 'araw1281',
 'para1318': 'sign1238',
 'pare1272': 'araw1281',
 'pata1261': 'nucl1710',
 'pata1262': 'cari1283',
 'paum1247': 'araw1282',
 'paun1241': 'araw1281',
 'paus1244': 'tupi1275',
 'pemo1245': 'cari1283',
 'pemo1248': 'cari1283',
 'peru1235': 'sign1238',
 'piap1246': 'araw1281',
 'piar1243': 'sali1297',
 'pich1237': 'araw1281',
 'pija1235': 'uncl1493',
 'pila1245': 'guai1249',
 'pira1253': 'unk',
 'pira1254': 'tuca1253',
 'pisa1244': 'unat1236',
 'play1240': 'guah1252',
 'poka1242': 'book1242',
 'pona1251': 'book1242',
 'poti1237': 'tupi1275',
 'poya1241': 'pano1259',
 'puel1244': 'unk',
 'puin1248': 'unk',
 'pume1238': 'unk',
 'puno1238': 'quec1387',
 'puqu1242': 'unk',
 'puri1262': 'puri1261',
 'puru1264': 'tupi1275',
 'qawa1238': 'kawe1237',
 'remo1248': 'pano1259',
 'resi1247': 'araw1281',
 'reye1240': 'pano1259',
 'rikb1245': 'nucl1710',
 'riog1239': 'indo1319',
 'runa1235': 'unat1236',
 'saba1268': 'namb1299',
 'saki1248': 'tupi1275',
 'sala1272': 'quec1387',
 'sala1273': 'tupi1275',
 'sali1298': 'sali1297',
 'salu1254': 'book1242',
 'sana1281': 'book1242',
 'sana1298': 'leng1261',
 'sanb1242': 'chib1249',
 'sanm1289': 'quec1387',
 'sant1432': 'quec1387',
 'sant1433': 'quec1387',
 'sanu1240': 'yano1268',
 'saop1235': 'nucl1710',
 'sape1238': 'unk',
 'sara1331': 'araw1281',
 'sara1340': 'indo1319',
 'sate1243': 'tupi1275',
 'seco1241': 'tuca1253',
 'sens1242': 'pano1259',
 'shan1283': 'pano1259',
 'shar1245': 'pano1259',
 'shin1267': 'unat1236',
 'ship1254': 'pano1259',
 'shua1257': 'jiva1245',
 'sihu1235': 'quec1387',
 'siki1239': 'book1242',
 'sion1247': 'tuca1253',
 'siri1273': 'tupi1275',
 'siri1274': 'tuca1253',
 'sivi1235': 'sign1238',
 'skep1238': 'indo1319',
 'sout2989': 'leng1261',
 'sout2990': 'quec1387',
 'sout2991': 'quec1387',
 'sout2992': 'quec1387',
 'sout2994': 'namb1299',
 'sout2996': 'ayma1253',
 'sout3127': 'araw1281',
 'sran1240': 'indo1319',
 'suru1261': 'tupi1275',
 'suru1262': 'tupi1275',
 'suru1263': 'araw1282',
 'suya1243': 'nucl1710',
 'taca1256': 'pano1259',
 'tama1338': 'cari1283',
 'tama1340': 'tuca1253',
 'tani1257': 'tuca1253',
 'tape1236': 'book1242',
 'tapi1253': 'tupi1275',
 'tapi1254': 'tupi1275',
 'tari1256': 'araw1281',
 'taru1236': 'unk',
 'tatu1247': 'tuca1253',
 'taus1253': 'unk',
 'tawa1278': 'namb1299',
 'tehu1242': 'chon1288',
 'temb1276': 'tupi1275',
 'tena1240': 'quec1387',
 'tenh1241': 'tupi1275',
 'tere1279': 'araw1281',
 'tete1252': 'book1242',
 'ticu1245': 'ticu1244',
 'ting1238': 'book1242',
 'tini1245': 'unk',
 'toba1268': 'leng1261',
 'toba1269': 'guai1249',
 'toba1282': 'indo1319',
 'toca1235': 'tupi1275',
 'tome1239': 'book1242',
 'tora1263': 'chap1271',
 'toro1255': 'pano1259',
 'toto1306': 'barb1265',
 'trem1235': 'unat1236',
 'trin1274': 'araw1281',
 'trin1276': 'indo1319',
 'trin1277': 'sign1238',
 'trio1238': 'cari1283',
 'truk1242': 'unat1236',
 'trum1247': 'unk',
 'tuca1252': 'tuca1253',
 'tuku1240': 'unat1236',
 'tupa1250': 'tupi1275',
 'tupi1272': 'tupi1275',
 'tupi1273': 'tupi1275',
 'tupi1274': 'tupi1275',
 'turi1247': 'tupi1275',
 'tuxa1239': 'unk',
 'tuxi1238': 'pano1259',
 'tuyu1244': 'tuca1253',
 'uamu1236': 'uncl1493',
 'ucay1237': 'araw1281',
 'umot1240': 'boro1281',
 'urar1246': 'unk',
 'urub1243': 'sign1238',
 'urub1250': 'tupi1275',
 'urue1240': 'tupi1275',
 'urug1238': 'sign1238',
 'urum1250': 'tupi1275',
 'urup1235': 'uncl1493',
 'uruu1244': 'uruc1242',
 'vene1237': 'sign1238',
 'vile1241': 'unk',
 'waim1253': 'cari1283',
 'waim1255': 'tuca1253',
 'waiw1244': 'cari1283',
 'wako1235': 'unat1236',
 'waor1240': 'unk',
 'wapi1253': 'araw1281',
 'wara1303': 'unk',
 'wari1268': 'chap1271',
 'wasu1238': 'unat1236',
 'waur1244': 'araw1281',
 'waya1269': 'cari1283',
 'waya1270': 'tupi1275',
 'wayo1238': 'tupi1275',
 'wayu1243': 'araw1281',
 'west2640': 'tupi1275',
 'west2651': 'chib1249',
 'wich1262': 'mata1289',
 'wich1263': 'mata1289',
 'wich1264': 'mata1289',
 'wira1264': 'tupi1275',
 'woun1238': 'choc1280',
 'xakr1238': 'nucl1710',
 'xava1240': 'nucl1710',
 'xere1240': 'nucl1710',
 'xeta1241': 'tupi1275',
 'xing1248': 'tupi1275',
 'xipa1240': 'tupi1275',
 'xipi1238': 'unat1236',
 'xiri1243': 'araw1281',
 'xokl1240': 'nucl1710',
 'xuku1239': 'unk',
 'yaba1248': 'cari1283',
 'yaba1249': 'araw1281',
 'yagu1244': 'peba1241',
 'yahu1241': 'tuca1253',
 'yala1242': 'unat1236',
 'yama1264': 'unk',
 'yame1242': 'peba1241',
 'yami1256': 'pano1259',
 'yana1272': 'quec1387',
 'yane1238': 'araw1281',
 'yano1261': 'yano1268',
 'yano1262': 'yano1268',
 'yari1235': 'book1242',
 'yaro1235': 'yano1268',
 'yauy1235': 'quec1387',
 'yavi1244': 'araw1281',
 'yawa1260': 'pano1259',
 'yawa1261': 'araw1281',
 'yine1238': 'araw1281',
 'yora1241': 'pano1259',
 'yucu1253': 'araw1281',
 'yuhu1238': 'nada1235',
 'yukp1241': 'cari1283',
 'yuqu1240': 'tupi1275',
 'yura1255': 'unk',
 'yuru1263': 'tuca1253',
 'yuwa1244': 'unk',
 'zapa1253': 'zapa1251',
 'zoee1240': 'tupi1275'}

In [24]:
## identifiquemos las familias únicas

## lista vacía
familias_unicas = []

## recorremos las familias
for familia in dict_glottocode_fam.values():
    ## si no está, la guardamos
    if familia not in familias_unicas:
        ## guardamos
        familias_unicas += [familia]

In [25]:
## juntemos las lenguas con la misma familia

## diccionario vacío
dict_fam_lenguas = {}

## definimos pares familia:[]
## recorremos las familias
for familia in familias_unicas:
    ## definimos los pares
    dict_fam_lenguas[familia] = []
    
## recorremos las lenguas
for lengua in dict_glottocode_fam.keys():
    ## guardamos las lenguas en las listas respectivas
    ## identificamos la familia
    familia = dict_glottocode_fam[lengua]
    ## guardamos
    dict_fam_lenguas[familia] += [lengua]

In [26]:
dict_fam_lenguas

{'guai1249': ['abip1241', 'kadi1248', 'moco1246', 'pila1245', 'toba1269'],
 'unk': ['abis1238',
  'aika1237',
  'anda1286',
  'ando1256',
  'arut1244',
  'cams1241',
  'cand1248',
  'cani1243',
  'cayu1262',
  'cofa1242',
  'fuln1247',
  'guat1253',
  'iran1263',
  'iton1250',
  'kano1245',
  'kunz1244',
  'kwaz1243',
  'leco1242',
  'lule1238',
  'maku1246',
  'mato1253',
  'moch1259',
  'mose1249',
  'movi1243',
  'muni1258',
  'omur1241',
  'otii1244',
  'paez1247',
  'pank1250',
  'pira1253',
  'puel1244',
  'puin1248',
  'pume1238',
  'puqu1242',
  'sape1238',
  'taru1236',
  'taus1253',
  'tini1245',
  'trum1247',
  'tuxa1239',
  'urar1246',
  'vile1241',
  'waor1240',
  'wara1303',
  'xuku1239',
  'yama1264',
  'yura1255',
  'yuwa1244'],
 'araw1281': ['acha1250',
  'ajyi1238',
  'apur1254',
  'araw1276',
  'asha1243',
  'ashe1272',
  'ashe1273',
  'ator1244',
  'bani1254',
  'bani1255',
  'bare1276',
  'baur1253',
  'cabi1241',
  'caqu1242',
  'cham1318',
  'chan1322',
  'curr1243',
  'enaw1238',
  'guan1270',
  'guar1293',
  'igna1246',
  'inap1242',
  'mach1267',
  'mach1268',
  'mand1448',
  'mapi1252',
  'mash1270',
  'mehi1240',
  'nant1250',
  'noma1263',
  'pali1279',
  'para1316',
  'pare1272',
  'paun1241',
  'piap1246',
  'pich1237',
  'resi1247',
  'sara1331',
  'sout3127',
  'tari1256',
  'tere1279',
  'trin1274',
  'ucay1237',
  'wapi1253',
  'waur1244',
  'wayu1243',
  'xiri1243',
  'yaba1249',
  'yane1238',
  'yavi1244',
  'yawa1261',
  'yine1238',
  'yucu1253'],
 'tupi1275': ['ache1246',
  'akun1241',
  'aman1266',
  'amun1246',
  'anam1249',
  'apia1248',
  'araw1273',
  'arik1264',
  'arua1261',
  'aura1243',
  'avac1239',
  'awet1244',
  'chir1286',
  'cint1239',
  'coca1259',
  'east2555',
  'emer1243',
  'gavi1246',
  'guaj1255',
  'guaj1256',
  'guar1292',
  'jora1240',
  'juma1249',
  'juru1256',
  'kaiw1246',
  'kama1373',
  'kari1311',
  'kari1317',
  'karo1305',
  'kaya1329',
  'kepk1241',
  'kuru1309',
  'maku1278',
  'mari1442',
  'mbya1239',
  'mund1330',
  'nhen1239',
  'omag1248',
  'pait1247',
  'para1311',
  'para1312',
  'para1313',
  'paus1244',
  'poti1237',
  'puru1264',
  'saki1248',
  'sala1273',
  'sate1243',
  'siri1273',
  'suru1261',
  'suru1262',
  'tapi1253',
  'tapi1254',
  'temb1276',
  'tenh1241',
  'toca1235',
  'tupa1250',
  'tupi1272',
  'tupi1273',
  'tupi1274',
  'turi1247',
  'urub1250',
  'urue1240',
  'urum1250',
  'waya1270',
  'wayo1238',
  'west2640',
  'wira1264',
  'xeta1241',
  'xing1248',
  'xipa1240',
  'yuqu1240',
  'zoee1240'],
 'jiva1245': ['achu1248', 'agua1253', 'huam1247', 'shua1257'],
 'nucl1710': ['acro1239',
  'apin1244',
  'arik1265',
  'cane1242',
  'coro1248',
  'djeo1235',
  'kain1272',
  'kara1500',
  'kaya1330',
  'krah1246',
  'kren1239',
  'krey1238',
  'krik1239',
  'maxa1247',
  'ofay1240',
  'pana1307',
  'para1315',
  'pata1261',
  'rikb1245',
  'saop1235',
  'suya1243',
  'xakr1238',
  'xava1240',
  'xere1240',
  'xokl1240'],
 'unat1236': ['agav1236',
  'agua1251',
  'alap1235',
  'arma1244',
  'barb1242',
  'hima1247',
  'kara1475',
  'miar1236',
  'more1262',
  'pank1235',
  'papa1263',
  'pisa1244',
  'runa1235',
  'shin1267',
  'trem1235',
  'truk1242',
  'tuku1240',
  'wako1235',
  'wasu1238',
  'xipi1238',
  'yala1242'],
 'cari1283': ['akaw1239',
  'akur1238',
  'apal1257',
  'baka1277',
  'cari1279',
  'chai1253',
  'cuma1240',
  'enap1235',
  'gali1262',
  'hixk1239',
  'ikpe1245',
  'japr1238',
  'kaxu1237',
  'kuik1246',
  'macu1259',
  'mapo1246',
  'maqu1238',
  'mati1253',
  'para1310',
  'pata1262',
  'pemo1245',
  'pemo1248',
  'tama1338',
  'trio1238',
  'waim1253',
  'waiw1244',
  'waya1269',
  'yaba1248',
  'yukp1241'],
 'pano1259': ['amah1246',
  'arao1248',
  'atsa1242',
  'capa1241',
  'cash1251',
  'cash1254',
  'cavi1250',
  'chac1251',
  'esee1248',
  'isco1239',
  'kaxa1239',
  'koru1247',
  'kuli1255',
  'maru1252',
  'mati1255',
  'mats1244',
  'nuku1263',
  'paca1246',
  'pano1254',
  'pano1255',
  'poya1241',
  'remo1248',
  'reye1240',
  'sens1242',
  'shan1283',
  'shar1245',
  'ship1254',
  'taca1256',
  'toro1255',
  'tuxi1238',
  'yami1256',
  'yawa1260',
  'yora1241'],
 'hara1260': ['amar1274', 'huac1244'],
 'quec1387': ['ambo1252',
  'areq1237',
  'ayac1239',
  'caja1238',
  'caja1239',
  'cald1236',
  'cana1262',
  'chac1250',
  'chim1302',
  'chin1483',
  'chiq1249',
  'clas1251',
  'coro1247',
  'cusc1236',
  'east2551',
  'hual1241',
  'huam1248',
  'huay1240',
  'huay1241',
  'imba1240',
  'inga1252',
  'jauj1238',
  'jung1240',
  'lamb1276',
  'loja1235',
  'marg1254',
  'napo1242',
  'nort2973',
  'nort2976',
  'nort2979',
  'nort2980',
  'paca1245',
  'pana1306',
  'puno1238',
  'sala1272',
  'sanm1289',
  'sant1432',
  'sant1433',
  'sihu1235',
  'sout2990',
  'sout2991',
  'sout2992',
  'tena1240',
  'yana1272',
  'yauy1235'],
 'zapa1251': ['ando1255',
  'arab1268',
  'aush1242',
  'cahu1268',
  'iqui1243',
  'zapa1253'],
 'leng1261': ['anga1316',
  'guan1268',
  'nort2971',
  'sana1298',
  'sout2989',
  'toba1268'],
 'chib1249': ['ango1257',
  'arhu1242',
  'bari1297',
  'barr1251',
  'bord1248',
  'cent2150',
  'chib1270',
  'chim1309',
  'cogu1240',
  'mala1522',
  'sanb1242',
  'west2651'],
 'choc1280': ['anse1238',
  'cara1271',
  'embe1259',
  'embe1260',
  'embe1261',
  'embe1262',
  'epen1239',
  'nort2972',
  'woun1238'],
 'tuca1253': ['arap1275',
  'bara1380',
  'cara1272',
  'cube1242',
  'desa1247',
  'guan1269',
  'kore1283',
  'maca1261',
  'macu1260',
  'miri1270',
  'orej1242',
  'pira1254',
  'seco1241',
  'sion1247',
  'siri1274',
  'tama1340',
  'tani1257',
  'tatu1247',
  'tuca1252',
  'tuyu1244',
  'waim1255',
  'yahu1241',
  'yuru1263'],
 'sign1238': ['arge1236',
  'boli1236',
  'braz1236',
  'chil1264',
  'colo1249',
  'ecua1243',
  'para1318',
  'peru1235',
  'sivi1235',
  'trin1277',
  'urub1243',
  'urug1238',
  'vene1237'],
 'araw1282': ['arua1263',
  'culi1244',
  'deni1241',
  'jama1261',
  'paum1247',
  'suru1263'],
 'barb1265': ['awac1239', 'chac1249', 'colo1256', 'guam1248', 'toto1306'],
 'zamu1243': ['ayor1240', 'cham1315'],
 'indo1319': ['berb1259',
  'cafu1238',
  'cari1275',
  'colo1254',
  'creo1235',
  'guia1246',
  'kari1301',
  'kwin1243',
  'lore1243',
  'ndyu1242',
  'pale1260',
  'papi1253',
  'riog1239',
  'sara1340',
  'skep1238',
  'sran1240',
  'toba1282',
  'trin1276'],
 'bora1262': ['bora1263', 'muin1242'],
 'boro1281': ['boro1282', 'otuk1240', 'umot1240'],
 'kaku1242': ['cacu1241', 'nuka1242'],
 'book1242': ['cagu1236',
  'cauc1241',
  'chil1283',
  'chip1236',
  'coxi1236',
  'coya1241',
  'cume1234',
  'emok1238',
  'iapa1241',
  'kabi1264',
  'kaka1269',
  'kamb1287',
  'kari1309',
  'mask1241',
  'mawa1271',
  'nata1238',
  'noca1240',
  'nucl1668',
  'omej1234',
  'poka1242',
  'pona1251',
  'salu1254',
  'sana1281',
  'siki1239',
  'tape1236',
  'tete1252',
  'ting1238',
  'tome1239',
  'yari1235'],
 'spee1234': ['call1235'],
 'uncl1493': ['cara1245',
  'kaim1235',
  'kamb1239',
  'kapi1248',
  'kari1255',
  'pija1235',
  'uamu1236',
  'urup1235'],
 'aust1307': ['cari1276'],
 'ayma1253': ['cent2142', 'jaqa1244', 'sout2996'],
 'cahu1265': ['chay1248', 'jebe1250'],
 'uruc1242': ['chip1262', 'uruu1244'],
 'chiq1253': ['chiq1248'],
 'hibi1242': ['chol1284', 'hibi1243'],
 'guah1252': ['cuib1242', 'guah1255', 'guay1257', 'maca1259', 'play1240'],
 'nada1235': ['daww1239', 'hupd1244', 'nade1244', 'yuhu1238'],
 'arau1255': ['huil1244', 'mapu1245'],
 'chap1271': ['iten1243', 'orow1243', 'tora1263', 'wari1268'],
 'mata1289': ['iyoj1235',
  'iyow1239',
  'maca1260',
  'niva1238',
  'wich1262',
  'wich1263',
  'wich1264'],
 'kama1371': ['kama1372'],
 'katu1274': ['kana1291', 'kata1270'],
 'namb1299': ['lako1248',
  'latu1238',
  'mama1278',
  'saba1268',
  'sout2994',
  'tawa1278'],
 'sali1297': ['maco1239', 'piar1243', 'sali1298'],
 'mixe1287': ['medi1245'],
 'huit1251': ['mini1256', 'muru1274', 'nonu1241', 'nupo1240', 'ocai1244'],
 'pidg1258': ['ndyu1241'],
 'yano1268': ['nina1238', 'sanu1240', 'yano1261', 'yano1262', 'yaro1235'],
 'chon1288': ['onaa1245', 'tehu1242'],
 'puri1261': ['puri1262'],
 'kawe1237': ['qawa1238'],
 'ticu1244': ['ticu1245'],
 'peba1241': ['yagu1244', 'yame1242']}

### Sails!

In [70]:
## ¿Y si queremos descargar los datos de Sails y leerlos con Python? Usamos la famosa librería pandas :)

## importamos la librería
import pandas as pd

## leemos los tres archivos de la carpeta "datos sails"
## usamos el separador, tab
## usamos el nombre de los archivos

## argex5-1
df_argex5_1 = pd.read_csv('datos sails/argex5-1.txt', sep='\t')

## argex5-2
df_argex5_2 = pd.read_csv('datos sails/argex5-2.txt', sep='\t')

## argex5-3
df_argex5_3 = pd.read_csv('datos sails/argex5-3.txt', sep='\t')

In [71]:
df_argex5_1

,iso-639-3,name,value,description,latitude,longitude,family
0,agr,Aguaruna,C,none,-5.300440,-77.921790,Chicham
1,apy,Apalaí,C,none,1.497920,-54.745700,Cariban
2,apu,Apurinã,C,none,-8.216920,-66.771410,Arawakan
3,arh,Arhuaco,C,none,10.701840,-73.636290,Chibchan
4,kwi,Awa-Cuaiquer,C,none,1.216525,-78.340135,Barbacoan
...,...,...,...,...,...,...,...
90,mtp,Wichí Lhamtés Nocten,C,none,-21.987995,-63.597110,Matacoan
91,xav,Xavánte,C,none,-14.301730,-52.436690,Nuclear-Macro-Je
92,yaa,Yaminahua,C,none,-9.884597,-71.596433,Pano-Tacanan
93,ame,Yanesha',C,none,-10.545390,-75.314970,Arawakan
94,yuz,Yuracaré,C,none,-16.747880,-65.122410,Yurakare

In [72]:
df_argex5_2

,iso-639-3,name,value,description,latitude,longitude,family
0,agr,Aguaruna,C,none,-5.300440,-77.921790,Chicham
1,apy,Apalaí,C,none,1.497920,-54.745700,Cariban
2,apu,Apurinã,C,none,-8.216920,-66.771410,Arawakan
3,arh,Arhuaco,B,suffix/enclitic,10.701840,-73.636290,Chibchan
4,kwi,Awa-Cuaiquer,C,none,1.216525,-78.340135,Barbacoan
...,...,...,...,...,...,...,...
90,mtp,Wichí Lhamtés Nocten,C,none,-21.987995,-63.597110,Matacoan
91,xav,Xavánte,C,none,-14.301730,-52.436690,Nuclear-Macro-Je
92,yaa,Yaminahua,B,suffix/enclitic,-9.884597,-71.596433,Pano-Tacanan
93,ame,Yanesha',C,none,-10.545390,-75.314970,Arawakan
94,yuz,Yuracaré,C,none,-16.747880,-65.122410,Yurakare

In [73]:
df_argex5_3

,iso-639-3,name,value,description,latitude,longitude,family
0,agr,Aguaruna,B,suffix/enclitic,-5.300440,-77.921790,Chicham
1,apy,Apalaí,C,none,1.497920,-54.745700,Cariban
2,apu,Apurinã,C,none,-8.216920,-66.771410,Arawakan
3,arh,Arhuaco,C,none,10.701840,-73.636290,Chibchan
4,kwi,Awa-Cuaiquer,B,suffix/enclitic,1.216525,-78.340135,Barbacoan
...,...,...,...,...,...,...,...
90,mtp,Wichí Lhamtés Nocten,C,none,-21.987995,-63.597110,Matacoan
91,xav,Xavánte,C,none,-14.301730,-52.436690,Nuclear-Macro-Je
92,yaa,Yaminahua,C,none,-9.884597,-71.596433,Pano-Tacanan
93,ame,Yanesha',C,none,-10.545390,-75.314970,Arawakan
94,yuz,Yuracaré,C,none,-16.747880,-65.122410,Yurakare

In [74]:
df_argex5_1['name']

0                 Aguaruna
1                   Apalaí
2                  Apurinã
3                  Arhuaco
4             Awa-Cuaiquer
              ...
90    Wichí Lhamtés Nocten
91                 Xavánte
92               Yaminahua
93                Yanesha'
94                Yuracaré
Name: name, Length: 95, dtype: object

In [75]:
## ¿Cómo podríamos usar diccionarios para representar esta información?

## un detalle sobre pandas dataframes
## con list() transformamos una columna en lista
lenguas = list(df_argex5_1['name'])

In [76]:
lenguas[:10]

['Aguaruna',
 'Apalaí',
 'Apurinã',
 'Arhuaco',
 'Awa-Cuaiquer',
 'Awetí',
 'Ayacucho Quechua',
 'Baure',
 'Bora',
 'Bororo']

In [7]:
## valores para los distintos rasgos

## argex5-1
valores_argex5_1 = list(df_argex5_1['value'])

## argex5-2
valores_argex5_2 = list(df_argex5_2['value'])

## argex5-3
valores_argex5_3 = list(df_argex5_3['value'])

In [8]:
valores_argex5_1[:10]

['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C']

In [9]:
valores_argex5_2[:10]

['C', 'C', 'C', 'B', 'C', 'C', 'C', 'C', 'C', 'C']

In [10]:
valores_argex5_3[:10]

['B', 'C', 'C', 'C', 'B', 'C', 'B', 'C', 'B', 'C']

In [77]:
## ¿Qué diccionarios podrían construirse? 

## idea 1: tres diccionarios - argex5_X_dict = {lengua1:valor, lengua2:valor, ...}

## diccionario vacío rasgo argex5-1
argex5_1_dict = {}

## recorremos las lenguas
for i in range(len(lenguas)):
    ## extraemos el valor
    valor = valores_argex5_1[i]
    ## guardamos en el diccionario
    argex5_1_dict[lenguas[i]] = valor

In [78]:
argex5_1_dict

{'Aguaruna': 'C',
 'Apalaí': 'C',
 'Apurinã': 'C',
 'Arhuaco': 'C',
 'Awa-Cuaiquer': 'C',
 'Awetí': 'C',
 'Ayacucho Quechua': 'C',
 'Baure': 'C',
 'Bora': 'C',
 'Bororo': 'C',
 'Cajamarca Quechua': 'C',
 'Callawalla': 'C',
 'Canela': 'C',
 'Cavineña': 'C',
 'Central Aymara': 'C',
 'Chimila': 'C',
 'Chipaya': 'C',
 'Cholón': 'C',
 'Cocama-Cocamilla': 'C',
 'Cubeo': 'C',
 'Cusco Quechua': 'C',
 'Desano': 'C',
 'Dâw': 'C',
 'Emerillon': 'C',
 'Gavião Do Jiparaná': 'C',
 'Guató': 'C',
 'Hixkaryána': 'C',
 'Huallaga Huánuco Quechua': 'C',
 'Huangascar-Topara-Yauyos Quechua': 'C',
 'Huaylas Ancash Quechua': 'C',
 'Hupdë': 'C',
 'Ikpeng': 'C',
 'Imbabura Highland Quichua': 'C',
 'Inga': 'C',
 'Itonama': 'C',
 'Jamamadí': 'C',
 'Jaqaru': 'C',
 'Jauja Wanca Quechua': 'C',
 'Jurúna': 'C',
 'Kamayurá': 'C',
 'Kanoê': 'C',
 'Karitiâna': 'C',
 'Karo (Brazil)': 'C',
 'Katukína-Kanamarí': 'C',
 'Kwaza': 'C',
 'Lakondê': 'C',
 'Leco': 'C',
 'Lokono': 'C',
 'Makuráp': 'C',
 'Mapudungun': 'C',
 'Matsés': 'C',
 'Mochica': 'C',
 'Mocoví': 'C',
 'Mosetén': 'C',
 'Movima': 'C',
 'Mundurukú': 'C',
 'Muniche': 'C',
 'Nhengatu': 'C',
 'Ninam': 'C',
 'North Junín Quechua': 'C',
 'Northern Emberá': 'B',
 'Pacaraos Quechua': 'C',
 'Parecís': 'C',
 'Pilagá': 'C',
 'Puinave': 'C',
 'Páez': 'C',
 'Rikbaktsa': 'C',
 'Sabanê': 'C',
 'Sakirabia': 'C',
 'Salasaca Highland Quichua': 'C',
 'San Martín Quechua': 'C',
 'Santiago del Estero Quichua': 'C',
 'Sateré-Mawé': 'C',
 'Shawi': 'C',
 'Shipibo-Conibo': 'C',
 'Shuar': 'B',
 'South Bolivian Quechua': 'C',
 'Southern Pastaza Quechua': 'C',
 'Tapieté': 'C',
 'Tariana': 'C',
 'Tehuelche': 'B',
 'Tena Lowland Quichua': 'C',
 'Trió': 'C',
 'Trumai': 'C',
 'Tsafiki': 'C',
 'Urarina': 'C',
 'Uru': 'C',
 'Warao': 'C',
 'Wari': 'C',
 'Wayoró': 'C',
 'Wichí Lhamtés Nocten': 'C',
 'Xavánte': 'C',
 'Yaminahua': 'C',
 "Yanesha'": 'C',
 'Yuracaré': 'C'}

In [13]:
## idea 2: {'argex5_1':{lengua1:'C',...},'argex5_2':{lengua1:'B',...},'argex5_3':{lengua1:'C',...}}

## idea 3: {lengua1:{'argex5_1':'C','argex5_2':'B','argex5_3':'B'}, ...}